stages:
  - some_stages
  - "postman\npostman_job:\n stage: postman\n before_script:\n - apt-get update -qq && apt-get install -y -qq curl\n - curl -sL https://deb.nodesource.com/setup_8.x | bash -\n - apt-get install -y nodejs\n - npm install newman -g\n script:\n- newman --version"
