stages:
    - test

postman_tests:
    stage: test
    image: 
        name: postman/newman_alpine33
        entrypoint: [""]
        postman_job:
  before_script:
  - apt-get update -qq && apt-get install -y -qq curl
  - curl -sL https://deb.nodesource.com/setup_8.x | bash -
  - apt-get install -y nodejs
  - npm install newman -g
    script:
        - newman --version
        - npm install -g newman-reporter-html
        - newman run NFA - Health checks CPD.postman_collection.json --reporters cli,html,junit --reporter-html-export report.html --reporter-junit-export report.xml
    artifacts:
        when: always
        paths:
            - report.html
        reports:
            junit: report.xml
